// <auto-generated />
namespace Salvis.App.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CustomUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CustomUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "201601300120348_CustomUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
