//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salvis.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Salvis.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambio de contraseña exitoso..
        /// </summary>
        public static string Account_ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("Account_ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿No tienes una cuenta?.
        /// </summary>
        public static string Account_DontHaveAccount {
            get {
                return ResourceManager.GetString("Account_DontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account_DuplicateEmail.
        /// </summary>
        public static string Account_DuplicateEmail {
            get {
                return ResourceManager.GetString("Account_DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account_DuplicateUserName.
        /// </summary>
        public static string Account_DuplicateUserName {
            get {
                return ResourceManager.GetString("Account_DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo es inválido y/o no coincide con el actual..
        /// </summary>
        public static string Account_ErrorInDelete {
            get {
                return ResourceManager.GetString("Account_ErrorInDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce tu usuario:.
        /// </summary>
        public static string Account_InputUserName {
            get {
                return ResourceManager.GetString("Account_InputUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account_InvalidEmail.
        /// </summary>
        public static string Account_InvalidEmail {
            get {
                return ResourceManager.GetString("Account_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidPassword.
        /// </summary>
        public static string Account_InvalidPassword {
            get {
                return ResourceManager.GetString("Account_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account_InvalidUserName.
        /// </summary>
        public static string Account_InvalidUserName {
            get {
                return ResourceManager.GetString("Account_InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva contraseña.
        /// </summary>
        public static string Account_NewPassword {
            get {
                return ResourceManager.GetString("Account_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te hemos enviado un correo con la confirmación del cambio de contraseña..
        /// </summary>
        public static string Account_PasswordConfirmationSent {
            get {
                return ResourceManager.GetString("Account_PasswordConfirmationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account_ProviderError.
        /// </summary>
        public static string Account_ProviderError {
            get {
                return ResourceManager.GetString("Account_ProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reiniciar contraseña.
        /// </summary>
        public static string Account_ResetPassword {
            get {
                return ResourceManager.GetString("Account_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear una nueva cuenta.
        /// </summary>
        public static string Account_TitleRegister {
            get {
                return ResourceManager.GetString("Account_TitleRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account_UserRejected.
        /// </summary>
        public static string Account_UserRejected {
            get {
                return ResourceManager.GetString("Account_UserRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vista completa.
        /// </summary>
        public static string AdvancedOptions {
            get {
                return ResourceManager.GetString("AdvancedOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planificador de Presupuesto.
        /// </summary>
        public static string Apps_BudgetPlanner {
            get {
                return ResourceManager.GetString("Apps_BudgetPlanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asesores / Consultores.
        /// </summary>
        public static string Audits {
            get {
                return ResourceManager.GetString("Audits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario y/o contraseña indicada no coincide..
        /// </summary>
        public static string BadCredentials {
            get {
                return ResourceManager.GetString("BadCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quincenal.
        /// </summary>
        public static string BiWeekly {
            get {
                return ResourceManager.GetString("BiWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuraciones.
        /// </summary>
        public static string Configurations {
            get {
                return ResourceManager.GetString("Configurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Contraseña.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escritorio.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deuda.
        /// </summary>
        public static string Debt {
            get {
                return ResourceManager.GetString("Debt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deudas.
        /// </summary>
        public static string Debts {
            get {
                return ResourceManager.GetString("Debts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diario.
        /// </summary>
        public static string Dialy {
            get {
                return ResourceManager.GetString("Dialy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La información que has introducido es inválida o incompleta..
        /// </summary>
        public static string Error_InputInvalid {
            get {
                return ResourceManager.GetString("Error_InputInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un error desconocido ocurrió. Por favor, compruebe los datos y vuelva a intentarlo. Si el problema persiste, póngase en contacto..
        /// </summary>
        public static string Error_VerifyAndTry {
            get {
                return ResourceManager.GetString("Error_VerifyAndTry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error interno. Intenta nuevamente..
        /// </summary>
        public static string ErrorInternal {
            get {
                return ResourceManager.GetString("ErrorInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en validación..
        /// </summary>
        public static string ErrorInValidation {
            get {
                return ResourceManager.GetString("ErrorInValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto Esperado.
        /// </summary>
        public static string ExpectedAmount {
            get {
                return ResourceManager.GetString("ExpectedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursos Externos.
        /// </summary>
        public static string ExtResources {
            get {
                return ResourceManager.GetString("ExtResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuota.
        /// </summary>
        public static string Fee {
            get {
                return ResourceManager.GetString("Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los campos con asterisco (*) son obligatorios..
        /// </summary>
        public static string FieldsRequired {
            get {
                return ResourceManager.GetString("FieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Final.
        /// </summary>
        public static string FinalDate {
            get {
                return ResourceManager.GetString("FinalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta.
        /// </summary>
        public static string Goal {
            get {
                return ResourceManager.GetString("Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Tu deuda se ha creado correctamente! Ya puedes empezar a gestionar sus cuotas..
        /// </summary>
        public static string Goal_DebtCreated {
            get {
                return ResourceManager.GetString("Goal_DebtCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Hasta cuándo tienes para pagar?.
        /// </summary>
        public static string Goal_DebtDateEnd {
            get {
                return ResourceManager.GetString("Goal_DebtDateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desde cuándo estás pagando?.
        /// </summary>
        public static string Goal_DebtDateInit {
            get {
                return ResourceManager.GetString("Goal_DebtDateInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string Goal_Details {
            get {
                return ResourceManager.GetString("Goal_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Seguro que deseas eliminar esta meta?.
        /// </summary>
        public static string Goal_MsgDeleteGoal {
            get {
                return ResourceManager.GetString("Goal_MsgDeleteGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has registrado una nueva operación recurrente. Ya puedes consultar los detalles de sus próximas operaciones..
        /// </summary>
        public static string Goal_RecurrentCreated {
            get {
                return ResourceManager.GetString("Goal_RecurrentCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Hasta cuándo piensas realizar esta operación?.
        /// </summary>
        public static string Goal_RecurrentDateEnd {
            get {
                return ResourceManager.GetString("Goal_RecurrentDateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Cuál es la próxima fecha?.
        /// </summary>
        public static string Goal_RecurrentDateInit {
            get {
                return ResourceManager.GetString("Goal_RecurrentDateInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿De qué monto dispone esta operación?.
        /// </summary>
        public static string Goal_RecurrentWhatAmount {
            get {
                return ResourceManager.GetString("Goal_RecurrentWhatAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Alguna categoría en particular?.
        /// </summary>
        public static string Goal_RecurrentWichCategory {
            get {
                return ResourceManager.GetString("Goal_RecurrentWichCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Cada qué tiempo realizas esta operación?.
        /// </summary>
        public static string Goal_RecurrentWichTimeIterval {
            get {
                return ResourceManager.GetString("Goal_RecurrentWichTimeIterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Bravo! ¡Te has propuesto una nueva meta de ahorro!.
        /// </summary>
        public static string Goal_SavingCreated {
            get {
                return ResourceManager.GetString("Goal_SavingCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Hasta cuándo piensas ahorrar?.
        /// </summary>
        public static string Goal_SavingDateEnd {
            get {
                return ResourceManager.GetString("Goal_SavingDateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desde cuándo estás ahorrando?.
        /// </summary>
        public static string Goal_SavingDateInit {
            get {
                return ResourceManager.GetString("Goal_SavingDateInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Qué cantidad deseas ahorrar?.
        /// </summary>
        public static string Goal_SavingWhatAmount {
            get {
                return ResourceManager.GetString("Goal_SavingWhatAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has eliminado la meta..
        /// </summary>
        public static string Goal_SuccessDelete {
            get {
                return ResourceManager.GetString("Goal_SuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Qué cantidad total debes pagar?.
        /// </summary>
        public static string Goal_WhatAmount {
            get {
                return ResourceManager.GetString("Goal_WhatAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Qué monto deseas ahorrar?.
        /// </summary>
        public static string Goal_WhatAmountToSave {
            get {
                return ResourceManager.GetString("Goal_WhatAmountToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Alguna nota o descripción?.
        /// </summary>
        public static string Goal_WhatDescription {
            get {
                return ResourceManager.GetString("Goal_WhatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Cada qué cantidad de tiempo?.
        /// </summary>
        public static string Goal_WichTimeInterval {
            get {
                return ResourceManager.GetString("Goal_WichTimeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metas.
        /// </summary>
        public static string Goals {
            get {
                return ResourceManager.GetString("Goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histórico.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es un sistema inteligente que sirve de apoyo y asistencia al usuario en la educación, planificación, gestión y continuidad financiera..
        /// </summary>
        public static string Home_WhatIs {
            get {
                return ResourceManager.GetString("Home_WhatIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto Ideal.
        /// </summary>
        public static string IdealAmount {
            get {
                return ResourceManager.GetString("IdealAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervalo.
        /// </summary>
        public static string Interval {
            get {
                return ResourceManager.GetString("Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar menos.
        /// </summary>
        public static string Less {
            get {
                return ResourceManager.GetString("Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biblioteca.
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar Sesión.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Seguro que deseas eliminar esté mensaje?.
        /// </summary>
        public static string Mailing_Delete_Msg {
            get {
                return ResourceManager.GetString("Mailing_Delete_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Mensaje.
        /// </summary>
        public static string Mailing_Delete_Title {
            get {
                return ResourceManager.GetString("Mailing_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De.
        /// </summary>
        public static string Mailing_From {
            get {
                return ResourceManager.GetString("Mailing_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandeja de entrada.
        /// </summary>
        public static string Mailing_Inbox {
            get {
                return ResourceManager.GetString("Mailing_Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responder.
        /// </summary>
        public static string Mailing_Reply {
            get {
                return ResourceManager.GetString("Mailing_Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string Mailing_Send {
            get {
                return ResourceManager.GetString("Mailing_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha enviado tu mensaje..
        /// </summary>
        public static string Mailing_Sent_Success {
            get {
                return ResourceManager.GetString("Mailing_Sent_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asunto.
        /// </summary>
        public static string Mailing_Subject {
            get {
                return ResourceManager.GetString("Mailing_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca el asunto.
        /// </summary>
        public static string Mailing_Subject_Placeholder {
            get {
                return ResourceManager.GetString("Mailing_Subject_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para.
        /// </summary>
        public static string Mailing_To {
            get {
                return ResourceManager.GetString("Mailing_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de.
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contáctanos.
        /// </summary>
        public static string Menu_Contact {
            get {
                return ResourceManager.GetString("Menu_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visor Mensual.
        /// </summary>
        public static string Menu_MonthlyViewer {
            get {
                return ResourceManager.GetString("Menu_MonthlyViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver todas.
        /// </summary>
        public static string Menu_SeeAllMessages {
            get {
                return ResourceManager.GetString("Menu_SeeAllMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciativa.
        /// </summary>
        public static string Menu_TheIdea {
            get {
                return ResourceManager.GetString("Menu_TheIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nosotros.
        /// </summary>
        public static string Menu_We {
            get {
                return ResourceManager.GetString("Menu_We", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensual.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visor Mensual.
        /// </summary>
        public static string MonthlyViewer {
            get {
                return ResourceManager.GetString("MonthlyViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar más.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multimedia.
        /// </summary>
        public static string Multimedia {
            get {
                return ResourceManager.GetString("Multimedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi Cuenta.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próxima Cuota.
        /// </summary>
        public static string NextShare {
            get {
                return ResourceManager.GetString("NextShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninguno(a).
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificación.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificaciones.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0k.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operaciones.
        /// </summary>
        public static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vista Panorámica.
        /// </summary>
        public static string PanoramicView {
            get {
                return ResourceManager.GetString("PanoramicView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planificador Presupuesto.
        /// </summary>
        public static string PlannerBudget {
            get {
                return ResourceManager.GetString("PlannerBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planificador de Ahorro.
        /// </summary>
        public static string PlannerSaving {
            get {
                return ResourceManager.GetString("PlannerSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push.
        /// </summary>
        public static string Push {
            get {
                return ResourceManager.GetString("Push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimestral.
        /// </summary>
        public static string Quarterly {
            get {
                return ResourceManager.GetString("Quarterly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurrentes.
        /// </summary>
        public static string Recurrent {
            get {
                return ResourceManager.GetString("Recurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Deseas realmente eliminar esta operación recurrente?.
        /// </summary>
        public static string Recurrent_DeleteOperation {
            get {
                return ResourceManager.GetString("Recurrent_DeleteOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurrent_DeleteOperationQuestion.
        /// </summary>
        public static string Recurrent_DeleteOperationQuestion {
            get {
                return ResourceManager.GetString("Recurrent_DeleteOperationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operaciones Recurrentes.
        /// </summary>
        public static string Recurrent_Header {
            get {
                return ResourceManager.GetString("Recurrent_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordarme.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahorro.
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahorros.
        /// </summary>
        public static string Savings {
            get {
                return ResourceManager.GetString("Savings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar....
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Contenido:.
        /// </summary>
        public static string SearchInputOptions {
            get {
                return ResourceManager.GetString("SearchInputOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Búsqueda por:.
        /// </summary>
        public static string SearchInputProveedor {
            get {
                return ResourceManager.GetString("SearchInputProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Términos de Búsqueda:.
        /// </summary>
        public static string SearchInputTerm {
            get {
                return ResourceManager.GetString("SearchInputTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar todos.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona la categoría.
        /// </summary>
        public static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Seleccione una opción --.
        /// </summary>
        public static string SelectOption {
            get {
                return ResourceManager.GetString("SelectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asesor Inteligente.
        /// </summary>
        public static string SmartAdvisor {
            get {
                return ResourceManager.GetString("SmartAdvisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS.
        /// </summary>
        public static string Sms {
            get {
                return ResourceManager.GetString("Sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Inicio.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consejos.
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Meta.
        /// </summary>
        public static string TitleDeleteGoal {
            get {
                return ResourceManager.GetString("TitleDeleteGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herramientas.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitante.
        /// </summary>
        public static string Visit {
            get {
                return ResourceManager.GetString("Visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semanal.
        /// </summary>
        public static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido a.
        /// </summary>
        public static string WelcomeTo {
            get {
                return ResourceManager.GetString("WelcomeTo", resourceCulture);
            }
        }
    }
}
